const constants = {
  ADD_RECT: 'ADD_RECT',
  CHANGE_COORD: 'CHANGE_COORD',
  ADD_LINE: 'ADD_LINE',
  REMOVE_LINE: 'REMOVE_LINE',
  DRAW_LINE_START: 'DRAW_LINE_START',
  DRAW_LINE_END: 'DRAW_LINE_END',
};

export default constants;
