const constants = {
  ADD_RECT: 'ADD_RECT',
  ADD_CONNECTION: 'ADD_CONNECTION',
  REMOVE_CONNECTION: 'REMOVE_CONNECTION',
  CHANGE_COORD: 'CHANGE_COORD',
  CHANGE_LINE_START: 'CHANGE_LINE_START',
  CHANGE_LINE_END: 'CHANGE_LINE_END',
  ADD_LINE: 'ADD_LINE',
  REMOVE_LINE: 'REMOVE_LINE',
  DRAW_LINE_START: 'DRAW_LINE_START',
  DRAW_LINE_END: 'DRAW_LINE_END',
};

export default constants;
